language: minimal

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose -f docker-compose-build.yaml build --parallel


after_success:
  - docker tag udagram-api-feed tmkha1989/udagram-api-feed:latest
  - docker tag udagram-api-user tmkha1989/udagram-api-user:latest
  - docker tag udagram-frontend tmkha1989/udagram-frontend:latest
  - docker tag reverseproxy tmkha1989/reverseproxy:latest

  - docker push tmkha1989/udagram-api-feed:latest
  - docker push tmkha1989/udagram-api-user:latest
  - docker push tmkha1989/udagram-frontend:latest
  - docker push tmkha1989/reverseproxy:latest


branches:
  only:
    - main