language: minimal

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose -f docker-compose-build.yaml build --parallel


after_success:
  - docker tag udagram-api-feed tmkha1989/udagram-api-feed:v2
  - docker tag udagram-api-user tmkha1989/udagram-api-user:v2
  - docker tag udagram-frontend tmkha1989/udagram-frontend:v2
  - docker tag reverseproxy tmkha1989/reverseproxy:v2

  - docker push tmkha1989/udagram-api-feed:v2
  - docker push tmkha1989/udagram-api-user:v2
  - docker push tmkha1989/udagram-frontend:v2
  - docker push tmkha1989/reverseproxy:v2


branches:
  only:
    - main