apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    service: api-feed
  type: ClusterIP