apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    service: api-user
  type: ClusterIP